### ISSUE TITLE
Sprint 3 (Week 3)

### ISSUE THREAD

**Issue by maxfie1d** [team-e-org/mobile#146]
## 梅 (minimum)

**Hayashi**
- [x] #32  SelectBoardPageの実装
- [x] #136 sign-in/sign-up のレスポンスの型 更新に対応
- [x] #143 カメラからの画像に対応する(まず調査の上で工数しだいで対応)
- [x] #155 BoardDetail画面の実装
- [x] #138 account画面表示時に No host specified in URI エラー
- [x] #135 ホーム画面でピン一覧の読み込みに失敗した場合にエラーを表示するようにする

- [x] #141 アカウント画面のボード一覧の読み込みでErrorStateになってもUI上では何も表示されない

**Ishida**
- [x] #145 テスト計画 (要議論)
- [x] #125 ログイン失敗時にエラーを出す
- [x] #113 deploygateを使った配布
- [x] #183 ビルド環境の切り替えの実装

**Both**

## 竹 (full)

- [x] #130 pin, board entitiesのvalidator実装
- [ ] #17 ピンの詳細画面でPinを保存できる
- [x] #129 ホーム画面を表示するたびに画像が再ロードされてしまう

## 松 (advanced)

- [ ] item1

## その他

- [ ] item1

**Comment by maxfie1d** [comment]
Sprint  3 終了につきclose
